# Generated by Django 4.2.1 on 2023-06-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='props',
            old_name='name',
            new_name='item',
        ),
    ]
