# Generated by Django 4.2.1 on 2023-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0004_alter_props_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='props',
            name='item',
            field=models.CharField(choices=[('1', '😀'), ('2', '🤠'), ('3', '🌻'), ('4', '💰'), ('5', '💀'), ('6', '❤'), ('7', '✨'), ('8', '👍'), ('9', '📈'), ('z', '🥳')], max_length=1),
        ),
    ]
