# Generated by Django 4.2.1 on 2023-06-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0005_alter_props_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='props',
            old_name='owner',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='props',
            name='item',
            field=models.CharField(choices=[('😀', '😀 smile'), ('🤠', '🤠 cowboy'), ('🌻', '🌻 sunflower'), ('💰', '💰 moneybagz'), ('💀', '💀 skull'), ('❤', '❤ heart'), ('✨', '✨ starz'), ('👍', '👍 thumby'), ('📈', '📈 stonkchart'), ('🥳', '🥳 celebrah')], max_length=15),
        ),
    ]
