# Generated by Django 4.2.1 on 2023-06-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0006_rename_owner_props_recipient_alter_props_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='props',
            old_name='recipient',
            new_name='owner',
        ),
    ]
