# Generated by Django 4.2.1 on 2023-06-15 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprops', '0008_props_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='props',
            name='owner',
        ),
        migrations.AddField(
            model_name='props',
            name='sender_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='props',
            name='sender_username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='props',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to=settings.AUTH_USER_MODEL),
        ),
    ]
