# Generated by Django 4.2.1 on 2023-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0010_alter_props_sender_id_alter_props_sender_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
