# Generated by Django 4.2.1 on 2023-06-15 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprops', '0011_props_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
